### ISSUE TITLE
File included twice, causes duplicate symbol error 

### ISSUE THREAD

**Issue by qrush** [archan937/motion-bundler#2]
Here's the error I'm getting:

```
duplicate symbol _MREP_0C4686FEED244B93B845620984127641 in:
    ./build/iPhoneSimulator-6.1-Development/objs/Users/qrush/Dev/doublebundle/app/controllers/concerns/events.rb.o
ld: 1 duplicate symbol for architecture i386
```

It looks like this is happening because events.rb is in .motion-bundle.rb twice:

https://github.com/qrush/doublebundle/blob/master/.motion-bundler.rb

Here's a repo to reproduce this:

https://github.com/qrush/doublebundle

**Comment by archan937** [comment]
I have fixed this error as of MotionBundler v0.1.4. Thanks for sending in the issue.
