### ISSUE TITLE
Why colorize dependency?

### ISSUE THREAD

**Issue by qrush** [archan937/motion-bundler#3]
This surprised me that motion-bundler added _another_ dependency to my project. I honestly don't need more. Why is this included, and would you consider removing it? It just seems strange and intrusive.

Edit - my initial reaction was of confusion. How did colorize become a dependency? I had to go hunting to figure out why, and eventually figured out it was in this gem. Just feels wrong.

**Comment by archan937** [comment]
Yeah, I agree. I used colorize just for printing messages in yellow, green and red. As of version 0.1.4, I have dropped colorize as gem dependency and defined String#yellow, String#green and String#red in MotionBundler itself. Cheers!

**Comment by qrush** [comment]
:+1:
